name: test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:
  initial:
    runs-on: ubuntu-latest
    steps:
      - run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          test -d ~/.linuxbrew && PATH="$HOME/.linuxbrew/bin:$HOME/.linuxbrew/sbin:$PATH"
          test -d /home/linuxbrew/.linuxbrew && PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"
          brew --prefix
          echo "$(brew --prefix)/bin" >> $GITHUB_PATH
          echo "$(brew --prefix)/sbin'" >> $GITHUB_PATH
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: rcs
          install: brew install
          directory: /usr/local
      - run: (cd __test__; . run.sh )
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
#  cached:
#    needs: initial
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: ./
#        id: action
#        with:
#          cache: workflow
#          tools: bmake
#      - run: (cd __test__; . run.sh )
#      - run: test "${{ steps.action.outputs.cache-hit }}" == true
#  no-cache:
#    needs: initial
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: ./
#        id: action
#        with:
#          cache: no
#          tools: bmake
#      - run: (cd __test__; . run.sh )
#      - run: test "${{ steps.action.outputs.cache-hit }}" != true
#  cache-gen:
#    needs: initial
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: ./
#        id: action
#        with:
#          cache: workflow
#          tools: bmake
#          cache-gen: v2
#      - run: (cd __test__; . run.sh )
#      - run: test "${{ steps.action.outputs.cache-hit }}" != true
